// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udnoifxiuyzhczldegrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkbm9pZnhpdXl6aGN6bGRlZ3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDQ5OTMsImV4cCI6MjA2MzY4MDk5M30.AjNqviqnOS0dTWEzfN3KjzUBGjWqHFSCDJIHJ7BZKzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);